name="soulknife"
description =[[]]
author ="artieYue"
version ="1.15"
forumthread = ""
api_version = 10
icon_atlas = "modicon.xml"
icon ="modicon.tex"
dst_compatible = true
all_clients_require_mod = true
client_only_mod = false
server_filter_tags = {""}
